# Generated by Django 5.2.7 on 2025-10-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
